# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DEFAULT_BRANCH: main # Usually master or main
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
IGNORE_GITIGNORED_FILES: true
JAVASCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_DEFAULT_STYLE: prettier
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "pnpm-.*.yaml"
ENABLE:
  - ACTION
  - KOTLIN
  - MARKDOWN
  - SPELL
  - TYPESCRIPT
  - YAML
PRINT_ALPACA: false # suppress fun output
KOTLIN_DETEKT_ARGUMENTS: "--baseline detekt-baseline.xml"
