main: net.nunnerycode.bukkit.mythicdrops.MythicDropsPlugin
name: ${project.build.name}
version: ${project.build.version}
authors: [ToppleTheNun, pur3pow3r]
softdepend: [Splatter, WorldEdit]

permissions:
    mythicdrops.command.spawn:
        default: op
        description: Allows player to use "/mythicdrops spawn" command.
    mythicdrops.command.spawn.wildcard:
        default: op
        description: Allows player to spawn in any tier.
    mythicdrops.command.give:
        default: op
        description: Allows player to use "/mythicdrops give" command.
    mythicdrops.command.give.wildcard:
        default: op
        description: Allows player to give any tier.
    mythicdrops.command.load:
        default: op
        description: Allows player to reload configuration files.
    mythicdrops.command.unidentified:
        default: op
        description: Allows player to use "/mythicdrops spawn" command.
    mythicdrops.command.identitytome:
        default: op
        description: Allows player to use "/mythicdrops tome" command.
    mythicdrops.command.customcreate:
        default: op
        description: Allows player to use "/mythicdrops customcreate" command.
    mythicdrops.command.custom:
        default: op
        description: Allows player to use "/mythicdrops custom" command.
    mythicdrops.command.gem:
        default: op
        description: Allows player to use "/mythicdrops gem" command.
    mythicdrops.command.tiers:
        default: op
        description: Allows player to use "/mythicdrops tiers" command.
    mythicdrops.command.bug:
        default: op
        description: Allows player to use "/mythicdrops bug" command.
    mythicdrops.command.*:
        description: Allows player to use all commands.
        children:
            mythicdrops.command.spawn: true
            mythicdrops.command.spawn.wildcard: true
            mythicdrops.command.give: true
            mythicdrops.command.give.wildcard: true
            mythicdrops.command.load: true
            mythicdrops.command.unidentified: true
            mythicdrops.command.identitytome: true
            mythicdrops.command.customcreate: true
            mythicdrops.command.custom: true
            mythicdrops.command.gem: true
            mythicdrops.command.tiers: true
            mythicdrops.command.bug: true
commands:
    mythicdrops:
        description: Base MythicDrops command.
        aliases: [mythicd, mdrops, md]