// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HomePage: typeof import('./components/HomePage.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    TeamPage: typeof import('./components/TeamPage.vue')['default']
  }
}
