import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val config: String = "io.pixeloutlaw.spigot-commons:config:" +
            Versions.io_pixeloutlaw_spigot_commons

    const val fanciful: String = "io.pixeloutlaw.spigot-commons:fanciful:" +
            Versions.io_pixeloutlaw_spigot_commons

    const val hilt: String = "io.pixeloutlaw.spigot-commons:hilt:" +
            Versions.io_pixeloutlaw_spigot_commons

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    const val se_bjurr_gitchangelog_git_changelog_gradle_plugin_gradle_plugin: String =
            "se.bjurr.gitchangelog.git-changelog-gradle-plugin:se.bjurr.gitchangelog.git-changelog-gradle-plugin.gradle.plugin:" +
            Versions.se_bjurr_gitchangelog_git_changelog_gradle_plugin_gradle_plugin

    const val io_pixeloutlaw_gradle_buildconfigkt_gradle_plugin: String =
            "io.pixeloutlaw.gradle.buildconfigkt:io.pixeloutlaw.gradle.buildconfigkt.gradle.plugin:" +
            Versions.io_pixeloutlaw_gradle_buildconfigkt_gradle_plugin

    const val com_github_johnrengelman_shadow_gradle_plugin: String =
            "com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:" +
            Versions.com_github_johnrengelman_shadow_gradle_plugin

    const val com_diffplug_gradle_spotless_gradle_plugin: String =
            "com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:" +
            Versions.com_diffplug_gradle_spotless_gradle_plugin

    const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:" +
            Versions.io_gitlab_arturbosch_detekt_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    const val nebula_nebula_bintray_gradle_plugin: String =
            "nebula.nebula-bintray:nebula.nebula-bintray.gradle.plugin:" +
            Versions.nebula_nebula_bintray_gradle_plugin

    const val nebula_maven_publish_gradle_plugin: String =
            "nebula.maven-publish:nebula.maven-publish.gradle.plugin:" +
            Versions.nebula_maven_publish_gradle_plugin

    const val org_jetbrains_dokka_gradle_plugin: String =
            "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:" +
            Versions.org_jetbrains_dokka_gradle_plugin

    const val com_moowork_node_gradle_plugin: String =
            "com.moowork.node:com.moowork.node.gradle.plugin:" +
            Versions.com_moowork_node_gradle_plugin

    const val nebula_project_gradle_plugin: String =
            "nebula.project:nebula.project.gradle.plugin:" + Versions.nebula_project_gradle_plugin

    const val nebula_release_gradle_plugin: String =
            "nebula.release:nebula.release.gradle.plugin:" + Versions.nebula_release_gradle_plugin

    /**
     * https://junit.org/junit5/
     */
    const val junit_platform_launcher: String = "org.junit.platform:junit-platform-launcher"

    /**
     * https://github.com/ToppleTheNun/spigot-plugin-annotations
     */
    const val plugin_yml_annotations: String =
            "io.pixeloutlaw.minecraft.spigot:plugin-yml-annotations:" +
            Versions.plugin_yml_annotations

    /**
     * https://github.com/square/moshi
     */
    const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:" +
            Versions.moshi_kotlin_codegen

    /**
     * https://github.com/ToppleTheNun/spigot-plugin-annotations
     */
    const val plugin_yml_processor: String =
            "io.pixeloutlaw.minecraft.spigot:plugin-yml-processor:" + Versions.plugin_yml_processor

    /**
     * https://github.com/PixelOutlaw/config-migrator
     */
    const val config_migrator: String = "io.pixeloutlaw.minecraft.spigot:config-migrator:" +
            Versions.config_migrator

    /**
     * https://bstats.org/
     */
    const val bstats_bukkit: String = "org.bstats:bstats-bukkit:" + Versions.bstats_bukkit

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter:" + Versions.junit_jupiter

    /**
     * http://assertj.org
     */
    const val assertj_core: String = "org.assertj:assertj-core:" + Versions.assertj_core

    /**
     * https://commons.apache.org/proper/commons-text
     */
    const val commons_text: String = "org.apache.commons:commons-text:" + Versions.commons_text

    /**
     * https://github.com/mockito/mockito
     */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core

    /**
     * https://github.com/PixelOutlaw/worldguard-adapters
     */
    const val adapter_lib: String = "io.pixeloutlaw.worldguard:adapter-lib:" + Versions.adapter_lib

    const val spigot_api: String = "org.spigotmc:spigot-api:" + Versions.spigot_api

    const val acf_paper: String = "co.aikar:acf-paper:" + Versions.acf_paper

    /**
     * https://junit.org/junit5/
     */
    const val junit_bom: String = "org.junit:junit-bom:" + Versions.junit_bom

    /**
     * http://mockk.io
     */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk
}
