/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  const val acf_paper: String = "co.aikar:acf-paper:" + Versions.acf_paper

  const val com_diffplug_gradle_spotless_gradle_plugin: String =
      "com.diffplug.gradle.spotless:com.diffplug.gradle.spotless.gradle.plugin:" +
      Versions.com_diffplug_gradle_spotless_gradle_plugin

  const val com_github_johnrengelman_shadow_gradle_plugin: String =
      "com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:" +
      Versions.com_github_johnrengelman_shadow_gradle_plugin

  /**
   * https://github.com/shyiko/klob
   */
  const val klob: String = "com.github.shyiko.klob:klob:" + Versions.klob

  /**
   * https://github.com/zafarkhaja/jsemver
   */
  const val java_semver: String = "com.github.zafarkhaja:java-semver:" + Versions.java_semver

  const val auto_service: String = "com.google.auto.service:auto-service:" + Versions.auto_service

  /**
   * http://github.com/google/truth
   */
  const val truth: String = "com.google.truth:truth:" + Versions.truth

  const val com_gradle_build_scan_gradle_plugin: String =
      "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" +
      Versions.com_gradle_build_scan_gradle_plugin

  const val worldguard_bukkit: String = "com.sk89q.worldguard:worldguard-bukkit:" +
      Versions.worldguard_bukkit

  /**
   * https://github.com/square/moshi
   */
  const val moshi_adapters: String = "com.squareup.moshi:moshi-adapters:" +
      Versions.com_squareup_moshi

  /**
   * https://github.com/square/moshi
   */
  const val moshi_kotlin_codegen: String = "com.squareup.moshi:moshi-kotlin-codegen:" +
      Versions.com_squareup_moshi

  /**
   * https://github.com/square/moshi
   */
  const val moshi: String = "com.squareup.moshi:moshi:" + Versions.com_squareup_moshi

  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  const val detekt_cli: String = "io.gitlab.arturbosch.detekt:detekt-cli:" +
      Versions.io_gitlab_arturbosch_detekt

  const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
      "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:" +
      Versions.io_gitlab_arturbosch_detekt

  /**
   * http://mockk.io
   */
  const val mockk: String = "io.mockk:mockk:" + Versions.mockk

  const val io_pixeloutlaw_gradle_buildconfigkt_gradle_plugin: String =
      "io.pixeloutlaw.gradle.buildconfigkt:io.pixeloutlaw.gradle.buildconfigkt.gradle.plugin:" +
      Versions.io_pixeloutlaw_gradle_buildconfigkt_gradle_plugin

  /**
   * https://github.com/PixelOutlaw/spigot-plugin-parent
   */
  const val config: String = "io.pixeloutlaw.spigot-commons:config:" +
      Versions.io_pixeloutlaw_spigot_commons

  /**
   * https://github.com/PixelOutlaw/spigot-plugin-parent
   */
  const val fanciful: String = "io.pixeloutlaw.spigot-commons:fanciful:" +
      Versions.io_pixeloutlaw_spigot_commons

  /**
   * https://github.com/PixelOutlaw/spigot-plugin-parent
   */
  const val hilt: String = "io.pixeloutlaw.spigot-commons:hilt:" +
      Versions.io_pixeloutlaw_spigot_commons

  /**
   * http://junit.org
   */
  const val junit: String = "junit:junit:" + Versions.junit

  /**
   * https://commons.apache.org/proper/commons-text
   */
  const val commons_text: String = "org.apache.commons:commons-text:" + Versions.commons_text

  /**
   * https://bstats.org/
   */
  const val bstats_bukkit: String = "org.bstats:bstats-bukkit:" + Versions.bstats_bukkit

  const val org_jetbrains_dokka_gradle_plugin: String =
      "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:" +
      Versions.org_jetbrains_dokka_gradle_plugin

  const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
      "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
      Versions.org_jetbrains_kotlin_jvm_gradle_plugin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_annotation_processing_gradle: String =
      "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_scripting_compiler_embeddable: String =
      "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://junit.org/junit5/
   */
  const val junit_jupiter: String = "org.junit.jupiter:junit-jupiter:" + Versions.junit_jupiter

  /**
   * https://junit.org/junit5/
   */
  const val junit_platform_launcher: String = "org.junit.platform:junit-platform-launcher"

  /**
   * https://junit.org/junit5/
   */
  const val junit_vintage_engine: String = "org.junit.vintage:junit-vintage-engine"

  /**
   * https://junit.org/junit5/
   */
  const val junit_bom: String = "org.junit:junit-bom:" + Versions.junit_bom

  /**
   * https://github.com/mockito/mockito
   */
  const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core

  /**
   * http://www.spigotmc.org
   */
  const val spigot_api: String = "org.spigotmc:spigot-api:" + Versions.spigot_api

  const val pl_allegro_tech_build_axion_release_gradle_plugin: String =
      "pl.allegro.tech.build.axion-release:pl.allegro.tech.build.axion-release.gradle.plugin:" +
      Versions.pl_allegro_tech_build_axion_release_gradle_plugin
}
