main: net.nunnerycode.bukkit.mythicdrops.MythicDropsPlugin
name: ${project.build.name}
version: ${project.build.version}
authors: [ToppleTheNun, pur3pow3r]
softdepend: [ItemStats]

permissions:
    mythicdrops.command.spawn:
        default: op
        description: Allows player to use "/mythicdrops spawn" command.
    mythicdrops.command.spawn.wildcard:
        default: op
        description: Allows player to spawn in any tier.
    mythicdrops.command.give:
        default: op
        description: Allows player to use "/mythicdrops give" command.
    mythicdrops.command.give.wildcard:
        default: op
        description: Allows player to give any tier.
    mythicdrops.command.save:
        default: op
        description: Allows player to save configuration files.
    mythicdrops.command.load:
        default: op
        description: Allows player to reload configuration files.
    mythicdrops.command.*:
        description: Allows player to use all commands.
        children:
            mythicdrops.command.spawn: true
            mythicdrops.command.spawn.wildcard: true
            mythicdrops.command.give: true
            mythicdrops.command.give.wildcard: true
            mythicdrops.command.save: true
            mythicdrops.command.load: true
commands:
    mythicdrops:
        description: Base MythicDrops command.
        aliases: [mythicd, mdrops, md]